[build]
  publish = "public"
  command = "antora --html-url-extension-style=indexify --pull site.yml --generator ./lib/generator.js"

[build.environment]
  NODE_VERSION = "8"
  BUILD_ONLY = "true"
  ANTORA_CACHE_DIR = ".cache/antora"

[context.deploy-preview]
  command = "URL=$DEPLOY_PRIME_URL antora --html-url-extension-style=indexify --pull site.yml --generator ./lib/generator.js"
