[build]
  publish = "public"
  command = "./netlify-build.sh"

[build.environment]
  NODE_VERSION = "8"
  BUILD_ONLY = "true"
  ANTORA_CACHE_DIR = ".cache/antora"

[context.deploy-preview]
  command = "URL=$DEPLOY_PRIME_URL ./netlify-build.sh"
