[build]
  publish = "public"
  command = "./netlify-build.sh"

[build.environment]
  NODE_VERSION = "8"
  BUILD_ONLY = "true"
  ANTORA_CACHE_DIR = ".cache/antora"

[context.deploy-preview]
  command = "URL=$DEPLOY_PRIME_URL ./netlify-build.sh"

[[redirects]]
  from = "/blog/1.0/:slug/index.html"
  to = "/blog/:slug/index.html"

[[redirects]]
  from = "/blog/1.0/rss/feed.xml"
  to = "/blog/rss/feed.xml"

[[redirects]]
  from = "/blog/1.0/rss/feed.xml"
  to = "/blog/rss/feed.xml"

[[redirects]]
  from = "/blog/1.0/tag/:tag/index.html"
  to = "/blog/tag/:tag/index.html"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

    Link = """
    </_/stylesheets/main.min.css>; rel=preload; as=style, \
    </_/images/main.jpg>; rel=preload; as=image"""
