runtime:
  cache_dir: ./.cache/antora
site:
  title: Blog - Yuzu tech
  url: https://blog.yuzutech.fr
  start_page: blog::index.adoc
content:
  sources:
  #- url: '.'
  - url: https://gitlab-ci-token:dqVrbg_3GQyVFdJHjEsN@gitlab.com/yuzutech/blog.yuzutech.fr.git
    branches: master
    start_path: blog
ui:
  bundle:
    url: './ui/bundle'
asciidoc:
  attributes:
    hide-uri-scheme: ''
    icons: 'svg'
  extensions:
    - './lib/extensions/gist-block-macro'
    - './lib/extensions/prism-line-highlight-tree-processor'
output:
  dir: ./public
